/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/trade/all-payments/': RouteRecordInfo<'/trade/all-payments/', '/trade/all-payments', Record<never, never>, Record<never, never>>,
    '/trade/order/[id]': RouteRecordInfo<'/trade/order/[id]', '/trade/order/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/trade/order/pay/[id]': RouteRecordInfo<'/trade/order/pay/[id]', '/trade/order/pay/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/trade/order/pay/confirm/': RouteRecordInfo<'/trade/order/pay/confirm/', '/trade/order/pay/confirm', Record<never, never>, Record<never, never>>,
    '/trade/orders/': RouteRecordInfo<'/trade/orders/', '/trade/orders', Record<never, never>, Record<never, never>>,
  }
}
